language: java
jdk:
  - openjdk8
services:
  - docker
jobs:
  include:
    - stage: test
      script:
        - ./gradlew
        - ./gradlew check
        - ./gradlew jacocoTestReport
        - bash <(curl -s https://codecov.io/bash)

    - stage: build
      script: docker build -t test/app .
