language: java
jdk:
  - oraclejdk8
  - openjdk8
services:
  - docker
jobs:
  include:
    - stage: test
      script:
        - ./gradlew
        - ./gradlew jacocoTestReport coveralls

    - stage: build
      script: docker build -t test/app .
